version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    ports:
      - "8081:80"
    volumes:
      - /home/gautam/my-php-project:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy  
    networks:
      - app_network

  mysql:
    image: mysql:5.7 
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Testing@123  
      MYSQL_DATABASE: demo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/gautam/employees.sql:/docker-entrypoint-initdb.d/employees.sql
      
    networks:
      - app_network
    healthcheck:  
      test: ["CMD-SHELL", "mysqladmin ping -u root -pTesting@123"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
