version: "3.8"

services:
  php-app:
    image: gautam789/php-fullstack-app:latest
    ports:
      - "3003:80"
    environment:
      DB_HOST: mysql-app
      DB_USER: mydbuser
      DB_PASSWORD: mydbpass
      DB_NAME: mydbname
    networks:
      - app-net

  mysql-app:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mydbpass
      MYSQL_DATABASE: mydbname
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: mydbpass
    volumes:
      - db_data:/var/lib/mysql
      - ./employees.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: overlay
