version: '3.8'

services:
  php-app:
    image: gautam789/php-mysql-app:main
    ports:
      - "3002:80"
    depends_on:
      - mysql-app
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7
    container_name: mysql-app
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Use MYSQL_ROOT_PASSWORD, not MYSQL_ROOT_USERNAME
      MYSQL_DATABASE: demo_db
    volumes:
      - db_data:/var/lib/mysql
      - /home/gautam/employees.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    attachable: true
