version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    ports:
      - "3001:80"
    volumes:
      - /home/ubuntu/my-php-project:/var/www/html
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql-app
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Testing@123
      MYSQL_DATABASE: demo_db
    volumes:
      - mysql_data:/var/lib/mysql
      - /home/ubuntu/script.sql:/docker-entrypoint-initdb.d/script.sql
      - /home/ubuntu/employees.sql:/docker-entrypoint-initdb.d/employees.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
